
spring:
  #redis配置开始
  redis:
    database: 1
    host: 192.168.3.2 # Redis服务器地址
    port: 6379
    jedis:
      pool:
        max-active: 1024 # 连接池最大连接数（使用负值表示没有限制）
        max-wait: 10000 # 连接池最大阻塞等待时间（使用负值表示没有限制）
        max-idle: 200 # 连接池中的最大空闲连接
        min-idle: 0 # 连接池中的最小空闲连接
    block-when-exhausted: true
    timeout: 10000  #超时时间

